### ISSUE TITLE
panic when setting capability on a pipelined request to a dead server

### ISSUE THREAD

**Issue by edevil** [capnproto/capnproto-rust#297]
I'm calling an API that after pipelining 2 requests, attempts to build another one that takes a capability. When the server is up everything runs fine, but when the server is down I get a nasty panic:

```
thread ':<unnamed>' panicked at 'Called inject_cap() on a null capability table. You need to call imbue_mut() on this message before adding capabilities. ', /Users/acruz/.cargo/registry/src/github.com-1ecc6299db9ec823/capnp-0.14.10/src/private/layout.rs:23952:21
stack backtrace:
   0: std::panicking::begin_panic
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:616:12
   1: capnp::private::layout::CapTableBuilder::inject_cap
             at /Users/acruz/.cargo/registry/src/github.com-1ecc6299db9ec823/capnp-0.14.10/src/private/layout.rs:2395:21
   2: capnp::private::layout::wire_helpers::set_capability_pointer
             at /Users/acruz/.cargo/registry/src/github.com-1ecc6299db9ec823/capnp-0.14.10/src/private/layout.rs:1709:34
   3: capnp::private::layout::PointerBuilder::set_capability
             at /Users/acruz/.cargo/registry/src/github.com-1ecc6299db9ec823/capnp-0.14.10/src/private/layout.rs:2756:9
   4: worker::worker::rpc::worker_capnp::email_metadata::Builder::set_email_fwdr
```

Is there a way to prevent these panics when there is an issue with the server, but still take advantage of pipelining?

**Comment by dwrensha** [comment]
Oof. That should never happen. Can you give me a way to reproduce the problem?

**Comment by edevil** [comment]
I modified your hello world rpc example in https://github.com/edevil/capnproto-rust/commit/eadd90579889be68128fd4347d36eb9f4a8fa4bf

If I run both client and server, and then kill the server:
```
❯ RUST_BACKTRACE=1 cargo run client 127.0.0.1:4000 "Hello World"
    Finished dev [unoptimized + debuginfo] target(s) in 0.14s
     Running `/Users/acruz/work/vc/capnproto-rust/target/debug/hello-world client '127.0.0.1:4000' 'Hello World'`
received: Hello, Hello World!
received: Hello, Hello World!
received: Hello, Hello World!
thread 'main' panicked at 'Called inject_cap() on a null capability table. You need to call imbue_mut() on this message before adding capabilities.', capnp/src/private/layout.rs:2395:21
stack backtrace:
   0: std::panicking::begin_panic
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:616:12
   1: capnp::private::layout::CapTableBuilder::inject_cap
             at /Users/acruz/work/vc/capnproto-rust/capnp/src/private/layout.rs:2395:21
   2: capnp::private::layout::wire_helpers::set_capability_pointer
             at /Users/acruz/work/vc/capnproto-rust/capnp/src/private/layout.rs:1709:34
   3: capnp::private::layout::PointerBuilder::set_capability
             at /Users/acruz/work/vc/capnproto-rust/capnp/src/private/layout.rs:2756:9
   4: hello_world::hello_world_capnp::hello_world::hello_request::Builder::set_callback_cap
             at /Users/acruz/work/vc/capnproto-rust/target/debug/build/hello-world-1bacee64204fc9a7/out/hello_world_capnp.rs:227:9
   5: hello_world::client::main::{{closure}}::{{closure}}
             at ./client.rs:84:17
...
```

**Comment by dwrensha** [comment]
Thanks! I think https://github.com/capnproto/capnproto-rust/commit/e61861cf1924b959e28290a69a88dda6af98c03f should fix this.

**Comment by edevil** [comment]
Thank you, I can confirm it fixes the issue.
