### ISSUE TITLE
calculator example fails with java server: Cannot read capability pointer without capTable

### ISSUE THREAD

**Issue by bedwards** [capnproto/capnproto-rust#477]
Hi, is it possible to use a rust capnp-rpc client with a java server? I tried using the calculator example, but I get an exception on the java server (complaining the the rust client is broken, missing capTable.)

```
 org.capnproto.RpcException
 Cannot read capability pointer without capTable.
    at org.capnproto.RpcException.failed(RpcException.java:28)
    at org.capnproto.Capability.newBrokenClient(Capability.java:650)
    at org.capnproto.Capability.newBrokenCap(Capability.java:638)
    at org.capnproto.WireHelpers.readCapabilityPointer(WireHelpers.java:1452)
```

```
git@github.com:capnproto/capnproto-rust.git
commit b85e041a1852cd4b3a7d7860ef4fbe16369c73e9 (HEAD -> master, tag: capnp-v0.19.1, origin/master, origin/HEAD)
```

```
git@github.com:vaci/capnproto-java-rpc.git
commit 1a36fd894d163fc4279fb8b77a1bc4dc19c8182f (HEAD -> master, origin/master, origin/HEAD)
```

The schema are identical except the java-specific stuff...

```
 @0x85150b117366d14b;

-using Java = import "/capnp/java.capnp";
-$Java.package("org.capnproto.examples");
-$Java.outerClassname("Calc");
-
 interface Calculator {
```

**Comment by dwrensha** [comment]
I don't know very much about capnproto-rpc-java, which lives in a different repo: https://github.com/vaci/capnproto-java-rpc
You might try reporting this issue there.

**Comment by dwrensha** [comment]
Closing, because this looks to me like a bug in the java RPC implementation.
